=== TheTeaRex/cmpe226/assignment8/assignment8-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:complexType name="person_type">
        <xs:sequence>
            <xs:element name="id" type="xs:positiveInteger"/>
            <xs:element name="first" type="xs:string"/>
            <xs:element name="last" type="xs:string"/>
            <xs:element name="phone">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{3}-\d{4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="people_type">
        <xs:sequence>
            <xs:element ref="person" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="person" type="person_type"/>
    <xs:element name="people" type="people_type"/>
</xs:schema>

=== TheTeaRex/cmpe226/assignment8/assignment8-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="assignment8-2.xsd">
    <person>
        <id>010001</id>
        <first>Ronald</first>
        <last>Mak</last>
        <phone>154-487-5135</phone>
    </person>
    <person>
        <id>151345</id>
        <first>John</first>
        <last>Smith</last>
        <phone>876-511-8755</phone>
    </person>
    <person>
        <id>135846</id>
        <first>Mary</first>
        <last>Jane</last>
        <phone>546-786-5411</phone>
    </person>
    <person>
        <id>010051</id>
        <first>Paul</first>
        <last>Nguyen</last>
        <phone>145-548-2156</phone>
    </person>
    <person>
        <id>184321</id>
        <first>Peeta</first>
        <last>Mellark</last>
        <phone>545-547-5112</phone>
    </person>
    <person>
        <id>012485</id>
        <first>Tom</first>
        <last>Jones</last>
        <phone>751-457-5475</phone>
    </person>
    <person>
        <id>213448</id>
        <first>Mary</first>
        <last>Robins</last>
        <phone>321-454-7890</phone>
    </person>
</people>
